// <auto-generated />
using System;
using FitnessTracker.WPF.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessTracker.WPF.Migrations
{
    [DbContext(typeof(FitnessDbContext))]
    partial class FitnessDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FitnessTracker.WPF.Models.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DefaultReps")
                        .HasColumnType("int");

                    b.Property<int>("DefaultRestSeconds")
                        .HasColumnType("int");

                    b.Property<int>("DefaultSets")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Environment")
                        .HasColumnType("int");

                    b.Property<string>("EquipmentNeeded")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("EstimatedCaloriesPerRep")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("ExerciseId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("FitnessTracker.WPF.Models.NutritionSuggestion", b =>
                {
                    b.Property<int>("NutritionSuggestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AIPrompt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AIResponse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DailyMealPlan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAIGenerated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PostWorkoutMeal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PreWorkoutMeal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("RecommendedCalories")
                        .HasColumnType("int");

                    b.Property<int?>("RecommendedCarbsGrams")
                        .HasColumnType("int");

                    b.Property<int?>("RecommendedFatsGrams")
                        .HasColumnType("int");

                    b.Property<int?>("RecommendedProteinGrams")
                        .HasColumnType("int");

                    b.Property<DateTime>("SuggestionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkoutSessionId")
                        .HasColumnType("int");

                    b.HasKey("NutritionSuggestionId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("NutritionSuggestions");
                });

            modelBuilder.Entity("FitnessTracker.WPF.Models.ProgressRecord", b =>
                {
                    b.Property<int>("ProgressRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BackPhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal?>("BodyFatPercentage")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal?>("Chest")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FrontPhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal?>("Hips")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("LeftArm")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("LeftThigh")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("RightArm")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("RightThigh")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("SidePhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Waist")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ProgressRecordId");

                    b.HasIndex("UserId");

                    b.ToTable("ProgressRecords");
                });

            modelBuilder.Entity("FitnessTracker.WPF.Models.Set", b =>
                {
                    b.Property<int>("SetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DifficultyRating")
                        .HasColumnType("int");

                    b.Property<int?>("FormRating")
                        .HasColumnType("int");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int?>("RestSeconds")
                        .HasColumnType("int");

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("WorkoutSessionExerciseId")
                        .HasColumnType("int");

                    b.HasKey("SetId");

                    b.HasIndex("WorkoutSessionExerciseId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("FitnessTracker.WPF.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FitnessGoal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsAIEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PreferredEnvironment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PreferredUnit")
                        .HasColumnType("int");

                    b.Property<int>("ThemeMode")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FitnessTracker.WPF.Models.WorkoutPlan", b =>
                {
                    b.Property<int>("WorkoutPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AIPrompt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DaysPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DurationWeeks")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Environment")
                        .HasColumnType("int");

                    b.Property<int>("Goal")
                        .HasColumnType("int");

                    b.Property<bool>("IsAIGenerated")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WorkoutPlanId");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutPlans");
                });

            modelBuilder.Entity("FitnessTracker.WPF.Models.WorkoutPlanExercise", b =>
                {
                    b.Property<int>("WorkoutPlanExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int?>("PlannedReps")
                        .HasColumnType("int");

                    b.Property<int?>("PlannedRestSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("PlannedSets")
                        .HasColumnType("int");

                    b.Property<decimal?>("PlannedWeight")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("WorkoutPlanId")
                        .HasColumnType("int");

                    b.HasKey("WorkoutPlanExerciseId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("WorkoutPlanExercises");
                });

            modelBuilder.Entity("FitnessTracker.WPF.Models.WorkoutSession", b =>
                {
                    b.Property<int>("WorkoutSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AverageHeartRate")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DifficultyRating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EnergyLevel")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("TotalCaloriesBurned")
                        .HasColumnType("int");

                    b.Property<int?>("TotalDurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkoutPlanId")
                        .HasColumnType("int");

                    b.HasKey("WorkoutSessionId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("FitnessTracker.WPF.Models.WorkoutSessionExercise", b =>
                {
                    b.Property<int>("WorkoutSessionExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CompletedSets")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int?>("PlannedReps")
                        .HasColumnType("int");

                    b.Property<int?>("PlannedSets")
                        .HasColumnType("int");

                    b.Property<decimal?>("PlannedWeight")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("int");

                    b.HasKey("WorkoutSessionExerciseId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("WorkoutSessionExercises");
                });

            modelBuilder.Entity("FitnessTracker.WPF.Models.Exercise", b =>
                {
                    b.HasOne("FitnessTracker.WPF.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("FitnessTracker.WPF.Models.NutritionSuggestion", b =>
                {
                    b.HasOne("FitnessTracker.WPF.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessTracker.WPF.Models.WorkoutSession", "WorkoutSession")
                        .WithMany("NutritionSuggestions")
                        .HasForeignKey("WorkoutSessionId");

                    b.Navigation("User");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("FitnessTracker.WPF.Models.ProgressRecord", b =>
                {
                    b.HasOne("FitnessTracker.WPF.Models.User", "User")
                        .WithMany("ProgressRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessTracker.WPF.Models.Set", b =>
                {
                    b.HasOne("FitnessTracker.WPF.Models.WorkoutSessionExercise", "WorkoutSessionExercise")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutSessionExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutSessionExercise");
                });

            modelBuilder.Entity("FitnessTracker.WPF.Models.WorkoutPlan", b =>
                {
                    b.HasOne("FitnessTracker.WPF.Models.User", "User")
                        .WithMany("WorkoutPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessTracker.WPF.Models.WorkoutPlanExercise", b =>
                {
                    b.HasOne("FitnessTracker.WPF.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessTracker.WPF.Models.WorkoutPlan", "WorkoutPlan")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("FitnessTracker.WPF.Models.WorkoutSession", b =>
                {
                    b.HasOne("FitnessTracker.WPF.Models.User", "User")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessTracker.WPF.Models.WorkoutPlan", "WorkoutPlan")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("WorkoutPlanId");

                    b.Navigation("User");

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("FitnessTracker.WPF.Models.WorkoutSessionExercise", b =>
                {
                    b.HasOne("FitnessTracker.WPF.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessTracker.WPF.Models.WorkoutSession", "WorkoutSession")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("FitnessTracker.WPF.Models.User", b =>
                {
                    b.Navigation("ProgressRecords");

                    b.Navigation("WorkoutPlans");

                    b.Navigation("WorkoutSessions");
                });

            modelBuilder.Entity("FitnessTracker.WPF.Models.WorkoutPlan", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("WorkoutSessions");
                });

            modelBuilder.Entity("FitnessTracker.WPF.Models.WorkoutSession", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("NutritionSuggestions");
                });

            modelBuilder.Entity("FitnessTracker.WPF.Models.WorkoutSessionExercise", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
